import { create } from '@stylexjs/stylex'

const FG = 'var(--fgColor-default, var(--color-fg-default, #1f2328))'
const MUTED = 'var(--fgColor-muted, var(--color-fg-muted, #59636e))'
const HOVER = 'var(--bgColor-neutral-muted, var(--color-neutral-muted, rgba(175, 184, 193, 0.2)))'

export const menuStyles = create({
  panel: {
    position: 'fixed',
    left: 'var(--ghpin-menu-left, 0px)',
    top: 'var(--ghpin-menu-top, 0px)',
    maxHeight: 'var(--ghpin-menu-height, calc(100dvh - 16px))',
    zIndex: 10000,
    boxSizing: 'border-box',
    width: 256,
    maxWidth: 'calc(100dvw - 16px)',
    padding: 8,
    overflowY: 'auto',
    overscrollBehavior: 'contain',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--borderColor-muted, var(--color-border-muted, #d8dee4))',
    borderRadius: 'var(--borderRadius-large, 12px)',
    backgroundColor: 'var(--overlay-bgColor, var(--bgColor-default, #fff))',
    color: FG,
    boxShadow: 'var(--shadow-floating-small, 0 8px 24px rgba(140, 149, 159, 0.2))',
    fontFamily:
      'var(--fontStack-system, -apple-system, BlinkMacSystemFont, "Segoe UI", "Noto Sans", Helvetica, Arial, sans-serif)',
    fontSize: 14,
    lineHeight: '20px',
    textAlign: 'left',
  },
  heading: { paddingInline: 8, paddingTop: 4, paddingBottom: 8 },
  caption: { display: 'block', color: MUTED, fontSize: 12, lineHeight: '16px' },
  repository: { display: 'block', fontWeight: 600, overflowWrap: 'anywhere' },
  item: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    boxSizing: 'border-box',
    width: '100%',
    minHeight: 'var(--control-medium-size, 32px)',
    margin: 0,
    paddingBlock: 6,
    paddingInline: 8,
    borderWidth: 0,
    borderRadius: 'var(--borderRadius-medium, 6px)',
    backgroundColor: { default: 'transparent', ':hover': HOVER, ':focus-visible': HOVER },
    color: FG,
    fontFamily: 'inherit',
    fontSize: 'inherit',
    lineHeight: 'inherit',
    textAlign: 'left',
    cursor: 'pointer',
    outlineStyle: { default: 'none', ':focus-visible': 'solid' },
    outlineWidth: { default: 0, ':focus-visible': 2 },
    outlineColor: 'var(--focus-outlineColor, var(--fgColor-accent, #0969da))',
    outlineOffset: -2,
  },
  pending: { cursor: 'wait', opacity: 0.5 },
  icon: { display: 'block', width: 16, height: 16, flexShrink: 0, fill: 'currentColor' },
  leadingIcon: { color: MUTED },
  label: { flexGrow: 1, minWidth: 0 },
  check: { display: 'inline-flex', width: 16, height: 16, flexShrink: 0 },
  status: {
    display: 'block',
    margin: 0,
    padding: 8,
    color: MUTED,
    fontSize: 12,
    lineHeight: '16px',
  },
  error: { color: 'var(--fgColor-danger, #cf222e)' },
  separator: {
    height: 1,
    marginBlock: 8,
    marginInline: -8,
    backgroundColor: 'var(--borderColor-muted, var(--color-border-muted, #d8dee4))',
  },
})
