import { create } from '@stylexjs/stylex'

const SUBTLE = 'var(--bgColor-muted, var(--color-canvas-subtle, #f6f8fa))'
const FG = 'var(--fgColor-default, var(--color-fg-default, #1f2328))'
const MUTED = 'var(--fgColor-muted, var(--color-fg-muted, #59636e))'
const BORDER = 'var(--borderColor-default, var(--color-border-default, #d1d9e0))'
const ACCENT = 'var(--fgColor-accent, var(--color-accent-fg, #0969da))'
const SELECTED =
  'var(--underlineNav-borderColor-active, var(--color-primer-border-active, #fd8c73))'
const HOVER = 'var(--bgColor-neutral-muted, var(--color-neutral-muted, rgba(175, 184, 193, 0.2)))'

export const styles = create({
  host: { display: 'block', width: '100%', minWidth: 0 },
  floatingHost: { position: 'fixed', top: 0, left: 0, zIndex: 1002 },
  slot: { display: 'block', width: '100%', minWidth: 0, height: 'var(--ghpin-slot-height, auto)' },
  nativeStickyOffset: { top: 'var(--ghpin-sticky-top) !important' },
  measureFlow: { position: 'static !important', top: 'auto !important' },
  bar: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: { default: 16, '@media (max-width: 600px)': 8 },
    minWidth: 0,
    minHeight: 'var(--control-xlarge-size, 48px)',
    paddingTop: 'var(--base-size-8, 8px)',
    paddingBottom: 0,
    paddingInline: 'var(--stack-padding-normal, 16px)',
    boxSizing: 'border-box',
    boxShadow: 'inset 0 -1px var(--borderColor-muted, var(--color-border-muted, #d8dee4))',
    backgroundColor: SUBTLE,
    color: FG,
    fontFamily:
      'var(--fontStack-system, -apple-system, BlinkMacSystemFont, "Segoe UI", "Noto Sans", Helvetica, Arial, sans-serif)',
    fontSize: 14,
    lineHeight: '20px',
    textAlign: 'left',
  },
  icon: {
    display: 'block',
    width: 16,
    height: 16,
    flexShrink: 0,
    fill: 'currentColor',
    verticalAlign: 'middle',
  },
  avatarContainer: { display: 'inline-flex', flexShrink: 0, width: 20, height: 20 },
  avatar: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    width: 20,
    height: 20,
    borderRadius: 'var(--borderRadius-small, 4px)',
    objectFit: 'cover',
    backgroundColor: HOVER,
    color: MUTED,
    boxShadow:
      '0 0 0 1px var(--avatar-borderColor, var(--borderColor-muted, rgba(31, 35, 40, 0.15)))',
  },
  list: {
    display: 'flex',
    alignItems: 'center',
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    gap: 8,
    minWidth: 0,
    margin: 0,
    padding: 0,
    overflowX: 'auto',
    listStyle: 'none',
    scrollbarWidth: 'thin',
  },
  tab: {
    display: 'flex',
    alignItems: 'center',
    flexShrink: 0,
    position: 'relative',
    boxSizing: 'border-box',
    height: 'var(--base-size-32, 32px)',
    marginBottom: 'var(--base-size-8, 8px)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'transparent',
    borderRadius: 'var(--borderRadius-medium, 6px)',
    backgroundColor: 'transparent',
  },
  temporary: { borderStyle: 'dashed', borderColor: BORDER },
  indicator: {
    position: 'absolute',
    right: 0,
    bottom: 'calc(-1 * var(--base-size-8, 8px))',
    left: 0,
    height: 2,
    borderRadius: 2,
    backgroundColor: { default: SELECTED, '@media (forced-colors: active)': 'LinkText' },
    pointerEvents: 'none',
  },
  link: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    height: '100%',
    minWidth: 0,
    paddingInline: 'var(--base-size-8, 8px)',
    paddingBlock: 'var(--base-size-6, 6px)',
    boxSizing: 'border-box',
    borderTopLeftRadius: 'var(--borderRadius-medium, 6px)',
    borderBottomLeftRadius: 'var(--borderRadius-medium, 6px)',
    borderTopRightRadius: 'var(--borderRadius-medium, 6px)',
    borderBottomRightRadius: 'var(--borderRadius-medium, 6px)',
    backgroundColor: { default: 'transparent', ':hover': HOVER },
    transition: 'background-color 120ms ease-out',
    color: FG,
    textDecoration: 'none',
    whiteSpace: 'nowrap',
    outlineStyle: { default: 'none', ':focus-visible': 'solid' },
    outlineWidth: { default: 0, ':focus-visible': 2 },
    outlineColor: ACCENT,
    outlineOffset: -2,
  },
  splitLink: { borderTopRightRadius: 0, borderBottomRightRadius: 0 },
  name: {
    maxWidth: 'min(300px, 45vw)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    '::before': {
      content: 'attr(data-content)',
      display: 'block',
      height: 0,
      visibility: 'hidden',
      fontWeight: 600,
      whiteSpace: 'nowrap',
    },
  },
  selectedName: { fontWeight: 600 },
  button: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    gap: 4,
    height: '100%',
    minWidth: 28,
    margin: 0,
    paddingBlock: 0,
    paddingInline: 6,
    borderWidth: 0,
    borderTopLeftRadius: 0,
    borderBottomLeftRadius: 0,
    borderTopRightRadius: 'var(--borderRadius-medium, 6px)',
    borderBottomRightRadius: 'var(--borderRadius-medium, 6px)',
    backgroundColor: { default: 'transparent', ':hover': HOVER },
    transition: 'background-color 120ms ease-out',
    color: { default: MUTED, ':hover': FG },
    fontFamily: 'inherit',
    fontSize: 12,
    lineHeight: '20px',
    cursor: { default: 'pointer', ':disabled': 'wait' },
    opacity: { default: 1, ':disabled': 0.5 },
    outlineStyle: { default: 'none', ':focus-visible': 'solid' },
    outlineWidth: { default: 0, ':focus-visible': 2 },
    outlineColor: ACCENT,
    outlineOffset: -2,
  },
  pinButton: { color: ACCENT, fontWeight: 600 },
  pendingButton: { cursor: 'wait', opacity: 0.5 },
  scrollLock: { overflow: 'hidden', scrollbarGutter: 'stable' },
  dialog: {
    display: { default: 'none', ':modal': 'flex' },
    flexDirection: 'column',
    width: 320,
    maxWidth: 'calc(100dvw - 64px)',
    maxHeight: 'calc(100dvh - 64px)',
    margin: 'auto',
    padding: 0,
    borderWidth: 0,
    borderRadius: 'var(--borderRadius-large, 12px)',
    overflow: 'hidden',
    backgroundColor: 'var(--overlay-bgColor, var(--bgColor-default, #fff))',
    color: FG,
    boxShadow: 'var(--shadow-floating-small, 0 8px 24px rgba(140, 149, 159, 0.2))',
    fontFamily: 'inherit',
    fontSize: 14,
    lineHeight: '20px',
    textAlign: 'left',
    '::backdrop': { backgroundColor: 'var(--overlay-backdrop-bgColor, rgba(31, 35, 40, 0.5))' },
  },
  dialogHeader: {
    display: 'flex',
    alignItems: 'center',
    flexShrink: 0,
    padding: 8,
    boxShadow: `0 1px 0 ${BORDER}`,
  },
  dialogTitle: {
    flexGrow: 1,
    margin: 0,
    paddingInline: 8,
    paddingBlock: 6,
    fontSize: 'var(--text-body-size-medium, 14px)',
    fontWeight: 'var(--text-title-weight-large, 600)',
    lineHeight: '20px',
  },
  dialogBody: { padding: 16, overflowY: 'auto', overflowWrap: 'anywhere' },
  dialogText: { margin: 0 },
  dialogError: { marginBottom: 0, color: 'var(--fgColor-danger, #cf222e)' },
  dialogFooter: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    flexShrink: 0,
    gap: 8,
    padding: 16,
  },
  dialogButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: 'var(--control-medium-size, 32px)',
    minWidth: 32,
    paddingBlock: 0,
    paddingInline: 'var(--control-medium-paddingInline-normal, 12px)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--button-default-borderColor-rest, var(--borderColor-default, #d1d9e0))',
    borderRadius: 'var(--borderRadius-medium, 6px)',
    backgroundColor: {
      default: 'var(--button-default-bgColor-rest, var(--bgColor-muted, #f6f8fa))',
      ':hover': 'var(--button-default-bgColor-hover, var(--bgColor-neutral-muted, #eff2f5))',
    },
    color: FG,
    fontFamily: 'inherit',
    fontSize: 14,
    fontWeight: 500,
    lineHeight: '20px',
    cursor: 'pointer',
    outlineStyle: { default: 'none', ':focus-visible': 'solid' },
    outlineWidth: { default: 0, ':focus-visible': 2 },
    outlineColor: 'var(--focus-outlineColor, var(--fgColor-accent, #0969da))',
    outlineOffset: 2,
  },
  dialogClose: {
    paddingInline: 0,
    borderColor: 'transparent',
    backgroundColor: { default: 'transparent', ':hover': HOVER },
    color: MUTED,
  },
  empty: { paddingBlock: 6, color: MUTED, fontSize: 12, whiteSpace: 'nowrap' },
  status: {
    position: 'absolute',
    width: 1,
    height: 1,
    overflow: 'hidden',
    clipPath: 'inset(50%)',
    whiteSpace: 'nowrap',
  },
  error: {
    position: 'static',
    width: 'auto',
    height: 'auto',
    maxWidth: { default: 260, '@media (max-width: 600px)': 120 },
    clipPath: 'none',
    color: MUTED,
    fontSize: 12,
    whiteSpace: 'normal',
  },
})
